/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula15;


import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaCalculadoraCidadao extends javax.swing.JFrame {
    int tabIndex = 0;
    /**
     * Creates new form Tela
     */
    public TelaCalculadoraCidadao() {
        initComponents();
        Date date = new Date();
        datetime.setText(date.toString());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase1 = new javax.swing.JPanel();
        pnlBase2 = new javax.swing.JPanel();
        pnlBase3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        datetime = new javax.swing.JLabel();
        pnlBase4 = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();
        btnProxAba = new javax.swing.JButton();
        btnVoltAba = new javax.swing.JButton();
        pnlTabelas = new javax.swing.JTabbedPane();
        pnlTabela1 = new javax.swing.JPanel();
        pnlAplicReg = new javax.swing.JPanel();
        lblARNumMeses = new javax.swing.JLabel();
        txtARNumMeses = new javax.swing.JTextField();
        lblARTaxJuros = new javax.swing.JLabel();
        txtARTaxJuros = new javax.swing.JTextField();
        lblArValDep = new javax.swing.JLabel();
        txtARValDep = new javax.swing.JTextField();
        lblARValFinal = new javax.swing.JLabel();
        txtARValFinal = new javax.swing.JTextField();
        btnCalcAplicReg = new javax.swing.JButton();
        btnClearAplicReg = new javax.swing.JButton();
        pnlTabela2 = new javax.swing.JPanel();
        pnlFinancPrest = new javax.swing.JPanel();
        lblFPNumMeses = new javax.swing.JLabel();
        txtFPNumMeses = new javax.swing.JTextField();
        lblFPTaxJuros = new javax.swing.JLabel();
        txtFPTaxJuros = new javax.swing.JTextField();
        lblFPValPrest = new javax.swing.JLabel();
        txtFPValPrest = new javax.swing.JTextField();
        lblFPValFinal = new javax.swing.JLabel();
        txtFPValFinal = new javax.swing.JTextField();
        btnCalcFinanc = new javax.swing.JButton();
        btnClearFinanc = new javax.swing.JButton();
        pnlTabela3 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCalcFCap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblFCapNumMonths = new javax.swing.JLabel();
        txtFCapNumMonths = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFCapTaxMonth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFCapCapital = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFCapValFinal = new javax.swing.JTextField();
        btnFCapClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase1.setPreferredSize(new java.awt.Dimension(30, 50));

        javax.swing.GroupLayout pnlBase1Layout = new javax.swing.GroupLayout(pnlBase1);
        pnlBase1.setLayout(pnlBase1Layout);
        pnlBase1Layout.setHorizontalGroup(
            pnlBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlBase1Layout.setVerticalGroup(
            pnlBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase1, java.awt.BorderLayout.LINE_END);

        pnlBase2.setPreferredSize(new java.awt.Dimension(30, 300));

        javax.swing.GroupLayout pnlBase2Layout = new javax.swing.GroupLayout(pnlBase2);
        pnlBase2.setLayout(pnlBase2Layout);
        pnlBase2Layout.setHorizontalGroup(
            pnlBase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlBase2Layout.setVerticalGroup(
            pnlBase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase2, java.awt.BorderLayout.LINE_START);

        pnlBase3.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula15/imagens/Senaclogo_1.png"))); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calculadora do Cidadão");
        jPanel4.add(jLabel3);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione a opção de cálculo das abas abaixo");
        jPanel4.add(jLabel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        datetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        datetime.setText("Data e Hora");

        javax.swing.GroupLayout pnlBase3Layout = new javax.swing.GroupLayout(pnlBase3);
        pnlBase3.setLayout(pnlBase3Layout);
        pnlBase3Layout.setHorizontalGroup(
            pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBase3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBase3Layout.setVerticalGroup(
            pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBase3Layout.createSequentialGroup()
                .addGroup(pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBase3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datetime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBase3, java.awt.BorderLayout.PAGE_START);

        pnlBase4.setPreferredSize(new java.awt.Dimension(400, 50));

        lblCopyright.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("SENAC - 2024 - ₢ Desenvolvido pela Turma TDS23_2M");

        btnProxAba.setText("Prox. Aba");
        btnProxAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxAbaActionPerformed(evt);
            }
        });

        btnVoltAba.setText("Volt. Aba");
        btnVoltAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltAbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBase4Layout = new javax.swing.GroupLayout(pnlBase4);
        pnlBase4.setLayout(pnlBase4Layout);
        pnlBase4Layout.setHorizontalGroup(
            pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBase4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblCopyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addComponent(btnVoltAba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProxAba)
                .addGap(55, 55, 55))
        );
        pnlBase4Layout.setVerticalGroup(
            pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBase4Layout.createSequentialGroup()
                .addGroup(pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCopyright)
                    .addGroup(pnlBase4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltAba)
                            .addComponent(btnProxAba))))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBase4, java.awt.BorderLayout.PAGE_END);

        pnlAplicReg.setLayout(new java.awt.GridLayout(4, 0, 0, 7));

        lblARNumMeses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblARNumMeses.setText("          Número de meses:");
        pnlAplicReg.add(lblARNumMeses);

        txtARNumMeses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtARNumMesesFocusLost(evt);
            }
        });
        pnlAplicReg.add(txtARNumMeses);

        lblARTaxJuros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblARTaxJuros.setText("     Taxa de Juros Mensal:");
        pnlAplicReg.add(lblARTaxJuros);

        txtARTaxJuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtARTaxJurosFocusLost(evt);
            }
        });
        pnlAplicReg.add(txtARTaxJuros);

        lblArValDep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArValDep.setText("          Valor do Depósito:");
        pnlAplicReg.add(lblArValDep);

        txtARValDep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtARValDepFocusLost(evt);
            }
        });
        pnlAplicReg.add(txtARValDep);

        lblARValFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblARValFinal.setText("Valor ao final do Período:");
        pnlAplicReg.add(lblARValFinal);
        pnlAplicReg.add(txtARValFinal);

        btnCalcAplicReg.setText("Calcular");
        btnCalcAplicReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcAplicRegActionPerformed(evt);
            }
        });

        btnClearAplicReg.setText("Limpar");
        btnClearAplicReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAplicRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela1Layout = new javax.swing.GroupLayout(pnlTabela1);
        pnlTabela1.setLayout(pnlTabela1Layout);
        pnlTabela1Layout.setHorizontalGroup(
            pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(pnlAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTabela1Layout.setVerticalGroup(
            pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(pnlAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcAplicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pnlTabelas.addTab("Aplicação de depósitos regulares", pnlTabela1);

        pnlFinancPrest.setLayout(new java.awt.GridLayout(4, 0, 0, 7));

        lblFPNumMeses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFPNumMeses.setText("          Número de meses:");
        pnlFinancPrest.add(lblFPNumMeses);

        txtFPNumMeses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPNumMesesFocusLost(evt);
            }
        });
        pnlFinancPrest.add(txtFPNumMeses);

        lblFPTaxJuros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFPTaxJuros.setText("     Taxa de Juros Mensal:");
        pnlFinancPrest.add(lblFPTaxJuros);

        txtFPTaxJuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPTaxJurosFocusLost(evt);
            }
        });
        pnlFinancPrest.add(txtFPTaxJuros);

        lblFPValPrest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFPValPrest.setText("          Valor da Prestação:");
        pnlFinancPrest.add(lblFPValPrest);

        txtFPValPrest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFPValPrestFocusLost(evt);
            }
        });
        pnlFinancPrest.add(txtFPValPrest);

        lblFPValFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFPValFinal.setText("             Valor Financiado:");
        pnlFinancPrest.add(lblFPValFinal);
        pnlFinancPrest.add(txtFPValFinal);

        btnCalcFinanc.setText("Calcular");
        btnCalcFinanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcFinancActionPerformed(evt);
            }
        });

        btnClearFinanc.setText("Limpar");
        btnClearFinanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFinancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela2Layout = new javax.swing.GroupLayout(pnlTabela2);
        pnlTabela2.setLayout(pnlTabela2Layout);
        pnlTabela2Layout.setHorizontalGroup(
            pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(pnlFinancPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearFinanc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcFinanc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTabela2Layout.setVerticalGroup(
            pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(pnlFinancPrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearFinanc, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnCalcFinanc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pnlTabelas.addTab("Financiamento Prestações Fixas", pnlTabela2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btnCalcFCap.setText("Calcular");
        btnCalcFCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcFCapActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(260, 109));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, 7));

        lblFCapNumMonths.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFCapNumMonths.setText("Número de meses:");
        jPanel1.add(lblFCapNumMonths);

        txtFCapNumMonths.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCapNumMonthsFocusLost(evt);
            }
        });
        jPanel1.add(txtFCapNumMonths);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Taxa de Juros Mensal:");
        jPanel1.add(jLabel6);

        txtFCapTaxMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCapTaxMonthFocusLost(evt);
            }
        });
        jPanel1.add(txtFCapTaxMonth);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("             Capital Atual:");
        jPanel1.add(jLabel7);

        txtFCapCapital.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFCapCapitalFocusLost(evt);
            }
        });
        jPanel1.add(txtFCapCapital);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Valor obtido ao Final:");
        jPanel1.add(jLabel8);
        jPanel1.add(txtFCapValFinal);

        btnFCapClear.setText("Limpar");
        btnFCapClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCapClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela3Layout = new javax.swing.GroupLayout(pnlTabela3);
        pnlTabela3.setLayout(pnlTabela3Layout);
        pnlTabela3Layout.setHorizontalGroup(
            pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela3Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTabela3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnFCapClear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcFCap, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTabela3Layout.setVerticalGroup(
            pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcFCap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFCapClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pnlTabelas.addTab("Valor futuro de Capital", pnlTabela3);

        getContentPane().add(pnlTabelas, java.awt.BorderLayout.CENTER);
        pnlTabelas.getAccessibleContext().setAccessibleName("Aplicação de Depósitos Regulares");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcAplicRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcAplicRegActionPerformed
        //Capturar os valores que são digitados pelo o usuário
        
        double numMonths = Double.parseDouble(txtARNumMeses.getText());
        double taxMonths = Double.parseDouble(txtARTaxJuros.getText());
        double valDeposit = Double.parseDouble(txtARValDep.getText());
        double valFinal;
        
        Calculadora calc = new Calculadora();
        valFinal = calc.calcAplicDepoReg(numMonths, taxMonths, valDeposit);
        
        txtARValFinal.setText(String.valueOf(valFinal));
    }//GEN-LAST:event_btnCalcAplicRegActionPerformed

    private void btnClearAplicRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAplicRegActionPerformed
        // TODO add your handling code here:
        txtARNumMeses.setText("");
        txtARTaxJuros.setText("");
        txtARValDep.setText("");
        txtARValFinal.setText("");
    }//GEN-LAST:event_btnClearAplicRegActionPerformed

    private void btnVoltAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltAbaActionPerformed
        // TODO add your handling code here:
        if(tabIndex == 0){
        tabIndex = 2;
        pnlTabelas.setSelectedIndex(tabIndex);
        System.out.println("Tab changed current index:" + tabIndex);
        }else{
        tabIndex--;
        pnlTabelas.setSelectedIndex(tabIndex);
        System.out.println("Tab changed current index:" + tabIndex);
        }
        
    }//GEN-LAST:event_btnVoltAbaActionPerformed

    private void btnProxAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxAbaActionPerformed
        // TODO add your handling code here:
        if(tabIndex == 2){
        tabIndex = 0;
        pnlTabelas.setSelectedIndex(tabIndex);
         System.out.println("Tab changed current index:" + tabIndex);
        }else{
        tabIndex++;
        pnlTabelas.setSelectedIndex(tabIndex);
        System.out.println("Tab changed current index:" + tabIndex);
        }
    }//GEN-LAST:event_btnProxAbaActionPerformed

    private void btnCalcFinancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcFinancActionPerformed
        // TODO add your handling code here:
        
        double numMonths = Double.parseDouble(txtFPNumMeses.getText());
        double taxMonths = Double.parseDouble(txtFPTaxJuros.getText());
        double valPrest = Double.parseDouble(txtFPValPrest.getText());
        double valFinal;
        
        Calculadora calc = new Calculadora();
        
        valFinal = calc.calcFinancPrestFixas(numMonths, taxMonths, valPrest);
        
        txtFPValFinal.setText(String.valueOf(valFinal));
    }//GEN-LAST:event_btnCalcFinancActionPerformed

    private void btnClearFinancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFinancActionPerformed
        // TODO add your handling code here:
        
        txtFPNumMeses.setText("");
        txtFPTaxJuros.setText("");
        txtFPValPrest.setText("");
        txtFPValFinal.setText("");
        
    }//GEN-LAST:event_btnClearFinancActionPerformed

    private void txtFPNumMesesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPNumMesesFocusLost
        // TODO add your handling code here:
        
        try {
            if(txtFPNumMeses.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtFPNumMeses.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtFPNumMeses.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFPNumMeses.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFPNumMeses.grabFocus();
        }
        
    }//GEN-LAST:event_txtFPNumMesesFocusLost

    private void txtFPTaxJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPTaxJurosFocusLost
        // TODO add your handling code here:
        
        try {
            if(txtFPTaxJuros.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtFPTaxJuros.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtFPTaxJuros.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFPTaxJuros.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFPTaxJuros.grabFocus();
        }
    }//GEN-LAST:event_txtFPTaxJurosFocusLost

    private void txtFPValPrestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFPValPrestFocusLost
        // TODO add your handling code here:
        try {
            if(txtFPValPrest.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtFPValPrest.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtFPValPrest.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFPValPrest.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFPValPrest.grabFocus();
        }
        
    }//GEN-LAST:event_txtFPValPrestFocusLost

    private void txtARNumMesesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtARNumMesesFocusLost
        // TODO add your handling code here:
        try {
            if(txtARNumMeses.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtARNumMeses.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtARNumMeses.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtARNumMeses.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtARNumMeses.grabFocus();
        }
    }//GEN-LAST:event_txtARNumMesesFocusLost

    private void txtARTaxJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtARTaxJurosFocusLost
        // TODO add your handling code here:
        try {
            if(txtARTaxJuros.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtARTaxJuros.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtARTaxJuros.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtARTaxJuros.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtARTaxJuros.grabFocus();
        }
    }//GEN-LAST:event_txtARTaxJurosFocusLost

    private void txtARValDepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtARValDepFocusLost
        // TODO add your handling code here:
        try {
            if(txtARValDep.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtARValDep.grabFocus();
            }else{
                double NumMonths = Double.parseDouble(txtARValDep.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtARValDep.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtARValDep.grabFocus();
        }
        
    }//GEN-LAST:event_txtARValDepFocusLost

    private void btnCalcFCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcFCapActionPerformed
        // TODO add your handling code here:
        double numMonths = Double.parseDouble(txtFCapNumMonths.getText());
        double taxMonth = Double.parseDouble(txtFCapTaxMonth.getText());
        double capital = Double.parseDouble(txtFCapCapital.getText());
        double valFinal;
        Calculadora calc = new Calculadora();
        
        valFinal = calc.calcValorFCap(120, 0.83, 300);
        
        txtFCapValFinal.setText(String.valueOf(valFinal));
        
        
    }//GEN-LAST:event_btnCalcFCapActionPerformed

    private void btnFCapClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCapClearActionPerformed
        // TODO add your handling code here:
        txtFCapNumMonths.setText("");
        txtFCapTaxMonth.setText("");
        txtFCapCapital.setText("");
        txtFCapValFinal.setText("");
        
        
    }//GEN-LAST:event_btnFCapClearActionPerformed

    private void txtFCapNumMonthsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCapNumMonthsFocusLost
        // TODO add your handling code here:
        try {
            if(txtFCapNumMonths.getText().isEmpty()){
                txtFCapNumMonths.grabFocus();
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                
            }else{
                double NumMonths = Double.parseDouble(txtFCapNumMonths.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFCapNumMonths.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFCapNumMonths.grabFocus();
        }
        
    }//GEN-LAST:event_txtFCapNumMonthsFocusLost

    private void txtFCapTaxMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCapTaxMonthFocusLost
        // TODO add your handling code here:
        try {
            if(txtFCapTaxMonth.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtFCapTaxMonth.grabFocus();
                
            } else{
                double taxmonth = Double.parseDouble(txtFCapTaxMonth.getText());
            }
           
        } catch (Exception e) {
            System.out.println(e);
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFCapTaxMonth.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFCapTaxMonth.grabFocus();
        }
    }//GEN-LAST:event_txtFCapTaxMonthFocusLost

    private void txtFCapCapitalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFCapCapitalFocusLost
        // TODO add your handling code here:
        try {
            if(txtFCapCapital.getText().isEmpty()){
                String msg = "Campo está vazio";
                JOptionPane.showMessageDialog(null, msg);
                txtFCapCapital.grabFocus();
                
            }else{
                double Capital = Double.parseDouble(txtFCapCapital.getText());
            }
           
        } catch (Exception e) {
            String msg = "Valor inválido, preencha com válores numéricos";
            txtFCapCapital.setText("");
            JOptionPane.showMessageDialog(null, msg);
            txtFCapCapital.grabFocus();
        }
    }//GEN-LAST:event_txtFCapCapitalFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadoraCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadoraCidadao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcAplicReg;
    private javax.swing.JButton btnCalcFCap;
    private javax.swing.JButton btnCalcFinanc;
    private javax.swing.JButton btnClearAplicReg;
    private javax.swing.JButton btnClearFinanc;
    private javax.swing.JButton btnFCapClear;
    private javax.swing.JButton btnProxAba;
    private javax.swing.JButton btnVoltAba;
    private javax.swing.JLabel datetime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblARNumMeses;
    private javax.swing.JLabel lblARTaxJuros;
    private javax.swing.JLabel lblARValFinal;
    private javax.swing.JLabel lblArValDep;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblFCapNumMonths;
    private javax.swing.JLabel lblFPNumMeses;
    private javax.swing.JLabel lblFPTaxJuros;
    private javax.swing.JLabel lblFPValFinal;
    private javax.swing.JLabel lblFPValPrest;
    private javax.swing.JPanel pnlAplicReg;
    private javax.swing.JPanel pnlBase1;
    private javax.swing.JPanel pnlBase2;
    private javax.swing.JPanel pnlBase3;
    private javax.swing.JPanel pnlBase4;
    private javax.swing.JPanel pnlFinancPrest;
    private javax.swing.JPanel pnlTabela1;
    private javax.swing.JPanel pnlTabela2;
    private javax.swing.JPanel pnlTabela3;
    private javax.swing.JTabbedPane pnlTabelas;
    private javax.swing.JTextField txtARNumMeses;
    private javax.swing.JTextField txtARTaxJuros;
    private javax.swing.JTextField txtARValDep;
    private javax.swing.JTextField txtARValFinal;
    private javax.swing.JTextField txtFCapCapital;
    private javax.swing.JTextField txtFCapNumMonths;
    private javax.swing.JTextField txtFCapTaxMonth;
    private javax.swing.JTextField txtFCapValFinal;
    private javax.swing.JTextField txtFPNumMeses;
    private javax.swing.JTextField txtFPTaxJuros;
    private javax.swing.JTextField txtFPValFinal;
    private javax.swing.JTextField txtFPValPrest;
    // End of variables declaration//GEN-END:variables
}
