/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula13;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaAula13 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAula13
     */
    public TelaAula13() {
        initComponents();
        rbtJava.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        rbtJava = new javax.swing.JRadioButton();
        rbtJavaScript = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();
        btConfirm = new javax.swing.JButton();
        rbtPython = new javax.swing.JRadioButton();
        rbtCsharp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtJava.setText("Java");
        rbtJava.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtJavaStateChanged(evt);
            }
        });

        rbtJavaScript.setText("JavaScript");
        rbtJavaScript.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtJavaScriptStateChanged(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Qual é a melhor linguagem de programação do mundo?");

        btConfirm.setText("Conferir");
        btConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmActionPerformed(evt);
            }
        });

        rbtPython.setText("Python");
        rbtPython.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtPythonStateChanged(evt);
            }
        });

        rbtCsharp.setText("C#");
        rbtCsharp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtCsharpStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtJava, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtPython, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtJavaScript, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtCsharp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addGap(42, 42, 42)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtJava)
                    .addComponent(rbtJavaScript))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPython)
                    .addComponent(rbtCsharp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btConfirm)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
        if(rbtJava.isSelected()){
            String msg = "DEFINITIVAMENTE melhor do que o primo >:)";
            JOptionPane.showMessageDialog(null,msg);
        }else if(rbtJavaScript.isSelected()){
            String msg = "UGH *barulhos de vomito* *barulhos de vomito*";
            JOptionPane.showMessageDialog(null,msg);
        }else if(rbtPython.isSelected()){
            String msg = "Definitivamente uma das linguagens já feitas";
            JOptionPane.showMessageDialog(null,msg);
        }else if(rbtCsharp.isSelected()){
            String msg = "Muito boa muito boa :D";
            JOptionPane.showMessageDialog(null,msg);
        }
        
        
    }//GEN-LAST:event_btConfirmActionPerformed

    private void rbtJavaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtJavaStateChanged
        // TODO add your handling code here:
            if(rbtJava.isSelected()){
                rbtJavaScript.setSelected(false);
                rbtCsharp.setSelected(false);
                rbtPython.setSelected(false);
            }
            
            if(!rbtJava.isSelected()){
                if(!rbtJavaScript.isSelected() && !rbtPython.isSelected() && !rbtCsharp.isSelected()){
                    rbtJavaScript.setSelected(true);
                }
            }
    }//GEN-LAST:event_rbtJavaStateChanged

    private void rbtJavaScriptStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtJavaScriptStateChanged
        // TODO add your handling code here:
            if(rbtJavaScript.isSelected()){
                rbtJava.setSelected(false);
                rbtCsharp.setSelected(false);
                rbtPython.setSelected(false);
            }
            
            if(!rbtJavaScript.isSelected()){
                if(!rbtJava.isSelected() && !rbtPython.isSelected() && !rbtCsharp.isSelected()){
                    rbtJava.setSelected(true);
                }
            }
    }//GEN-LAST:event_rbtJavaScriptStateChanged

    private void rbtPythonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtPythonStateChanged
        // TODO add your handling code here:
            if(rbtPython.isSelected()){
                rbtJava.setSelected(false);
                rbtCsharp.setSelected(false);
                rbtJavaScript.setSelected(false);
            }
            
            if(!rbtPython.isSelected()){
                if(!rbtJava.isSelected() && !rbtCsharp.isSelected() && !rbtJavaScript.isSelected()){
                    rbtJava.setSelected(true);
                }
            }
    }//GEN-LAST:event_rbtPythonStateChanged

    private void rbtCsharpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtCsharpStateChanged
        // TODO add your handling code here:
        if(rbtCsharp.isSelected()){
                rbtJava.setSelected(false);
                rbtPython.setSelected(false);
                rbtJavaScript.setSelected(false);
            }
            
            if(!rbtCsharp.isSelected()){
                if(!rbtJava.isSelected() && !rbtPython.isSelected() && !rbtJavaScript.isSelected()){
                    rbtJava.setSelected(true);
                }
            }
            
    }//GEN-LAST:event_rbtCsharpStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirm;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JRadioButton rbtCsharp;
    private javax.swing.JRadioButton rbtJava;
    private javax.swing.JRadioButton rbtJavaScript;
    private javax.swing.JRadioButton rbtPython;
    // End of variables declaration//GEN-END:variables
}
