/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula14;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase1 = new javax.swing.JPanel();
        pnlBase2 = new javax.swing.JPanel();
        pnlBase3 = new javax.swing.JPanel();
        pnlBase4 = new javax.swing.JPanel();
        pnlTabelas = new javax.swing.JTabbedPane();
        pnlTabela1 = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        btnCapturaNome = new javax.swing.JButton();
        btnTrocaAba = new javax.swing.JButton();
        pnlTabela2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        btnCapturaGenero = new javax.swing.JButton();
        bntTrocaAba = new javax.swing.JButton();
        pnlTabela3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnTrocarAba = new javax.swing.JButton();
        btnCapturaALGO = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase1.setPreferredSize(new java.awt.Dimension(30, 50));

        javax.swing.GroupLayout pnlBase1Layout = new javax.swing.GroupLayout(pnlBase1);
        pnlBase1.setLayout(pnlBase1Layout);
        pnlBase1Layout.setHorizontalGroup(
            pnlBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlBase1Layout.setVerticalGroup(
            pnlBase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase1, java.awt.BorderLayout.LINE_END);

        pnlBase2.setPreferredSize(new java.awt.Dimension(30, 300));

        javax.swing.GroupLayout pnlBase2Layout = new javax.swing.GroupLayout(pnlBase2);
        pnlBase2.setLayout(pnlBase2Layout);
        pnlBase2Layout.setHorizontalGroup(
            pnlBase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlBase2Layout.setVerticalGroup(
            pnlBase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase2, java.awt.BorderLayout.LINE_START);

        pnlBase3.setPreferredSize(new java.awt.Dimension(400, 30));

        javax.swing.GroupLayout pnlBase3Layout = new javax.swing.GroupLayout(pnlBase3);
        pnlBase3.setLayout(pnlBase3Layout);
        pnlBase3Layout.setHorizontalGroup(
            pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlBase3Layout.setVerticalGroup(
            pnlBase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase3, java.awt.BorderLayout.PAGE_START);

        pnlBase4.setPreferredSize(new java.awt.Dimension(400, 30));

        javax.swing.GroupLayout pnlBase4Layout = new javax.swing.GroupLayout(pnlBase4);
        pnlBase4.setLayout(pnlBase4Layout);
        pnlBase4Layout.setHorizontalGroup(
            pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlBase4Layout.setVerticalGroup(
            pnlBase4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBase4, java.awt.BorderLayout.PAGE_END);

        lblNomeCompleto.setText("Nome completo");

        txtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoActionPerformed(evt);
            }
        });

        btnCapturaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testesaveicon2.png"))); // NOI18N
        btnCapturaNome.setText("Ok");
        btnCapturaNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCapturaNomeMouseEntered(evt);
            }
        });
        btnCapturaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaNomeActionPerformed(evt);
            }
        });

        btnTrocaAba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testearrowicon_1.png"))); // NOI18N
        btnTrocaAba.setText("Prox. Aba");
        btnTrocaAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaAbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela1Layout = new javax.swing.GroupLayout(pnlTabela1);
        pnlTabela1.setLayout(pnlTabela1Layout);
        pnlTabela1Layout.setHorizontalGroup(
            pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTrocaAba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapturaNome)
                .addContainerGap())
            .addGroup(pnlTabela1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlTabela1Layout.setVerticalGroup(
            pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(pnlTabela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturaNome)
                    .addComponent(btnTrocaAba)))
        );

        pnlTabelas.addTab("tab1", pnlTabela1);

        jLabel2.setText("Informação do Gênero");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o gênero", "Masculino", "Feminino", " " }));
        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });

        btnCapturaGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testesaveicon2.png"))); // NOI18N
        btnCapturaGenero.setText("Ok");
        btnCapturaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaGeneroActionPerformed(evt);
            }
        });

        bntTrocaAba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testearrowicon_1.png"))); // NOI18N
        bntTrocaAba.setText("Prox. Aba");
        bntTrocaAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTrocaAbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela2Layout = new javax.swing.GroupLayout(pnlTabela2);
        pnlTabela2.setLayout(pnlTabela2Layout);
        pnlTabela2Layout.setHorizontalGroup(
            pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntTrocaAba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapturaGenero)
                .addContainerGap())
        );
        pnlTabela2Layout.setVerticalGroup(
            pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(pnlTabela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturaGenero)
                    .addComponent(bntTrocaAba)))
        );

        pnlTabelas.addTab("tab2", pnlTabela2);

        jLabel3.setText("jLabel3");

        btnTrocarAba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testearrowicon_1.png"))); // NOI18N
        btnTrocarAba.setText("Prox. Aba");
        btnTrocarAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarAbaActionPerformed(evt);
            }
        });

        btnCapturaALGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula14/Imagens/testesaveicon2.png"))); // NOI18N
        btnCapturaALGO.setText("Ok");
        btnCapturaALGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturaALGOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabela3Layout = new javax.swing.GroupLayout(pnlTabela3);
        pnlTabela3.setLayout(pnlTabela3Layout);
        pnlTabela3Layout.setHorizontalGroup(
            pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabela3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabela3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrocarAba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapturaALGO)))
                .addContainerGap())
        );
        pnlTabela3Layout.setVerticalGroup(
            pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabela3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(pnlTabela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapturaALGO)
                    .addComponent(btnTrocarAba)))
        );

        pnlTabelas.addTab("tab3", pnlTabela3);

        getContentPane().add(pnlTabelas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoActionPerformed

    private void btnCapturaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaNomeActionPerformed
        // TODO add your handling code here:
        
        String fullName = txtNomeCompleto.getText();
        JOptionPane.showMessageDialog(null, "Nome:" + fullName);
        
    }//GEN-LAST:event_btnCapturaNomeActionPerformed

    private void btnCapturaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaGeneroActionPerformed
        // TODO add your handling code here:
        
        String selectedGender = cbxGenero.getSelectedItem().toString();
        JOptionPane.showMessageDialog(null,"Sexo:" + selectedGender);
    }//GEN-LAST:event_btnCapturaGeneroActionPerformed

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void btnTrocaAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaAbaActionPerformed
        // TODO add your handling code here:
        pnlTabelas.setSelectedIndex(1);
        System.out.println("Tab changed");
        
        
    }//GEN-LAST:event_btnTrocaAbaActionPerformed

    private void bntTrocaAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTrocaAbaActionPerformed
        // TODO add your handling code here:
        pnlTabelas.setSelectedIndex(2);
        System.out.println("Tab changed");
    }//GEN-LAST:event_bntTrocaAbaActionPerformed

    private void btnTrocarAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarAbaActionPerformed
        // TODO add your handling code here:
        pnlTabelas.setSelectedIndex(0);
        System.out.println("Tab changed");
    }//GEN-LAST:event_btnTrocarAbaActionPerformed

    private void btnCapturaALGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturaALGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapturaALGOActionPerformed

    private void btnCapturaNomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapturaNomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapturaNomeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntTrocaAba;
    private javax.swing.JButton btnCapturaALGO;
    private javax.swing.JButton btnCapturaGenero;
    private javax.swing.JButton btnCapturaNome;
    private javax.swing.JButton btnTrocaAba;
    private javax.swing.JButton btnTrocarAba;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JPanel pnlBase1;
    private javax.swing.JPanel pnlBase2;
    private javax.swing.JPanel pnlBase3;
    private javax.swing.JPanel pnlBase4;
    private javax.swing.JPanel pnlTabela1;
    private javax.swing.JPanel pnlTabela2;
    private javax.swing.JPanel pnlTabela3;
    private javax.swing.JTabbedPane pnlTabelas;
    private javax.swing.JTextField txtNomeCompleto;
    // End of variables declaration//GEN-END:variables
}
