/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UsuarioController;
import Model.UsuarioModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaOperCadastroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaOperCadastroUsuarios
     */
    public TelaOperCadastroUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        pnlImagem = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        pblTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pblBottom = new javax.swing.JPanel();
        pnlBotoes = new javax.swing.JPanel();
        btnAtualiza = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        btnDeletarUsuario = new javax.swing.JButton();
        btnAtualizaUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlRight = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDadosUsuarios = new javax.swing.JTable();
        lblFiltro = new javax.swing.JLabel();
        txtNomeFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP Assistência :: Cadastro :: Manutenção de Cadastro de Usuários");
        setResizable(false);

        pnlBase.setLayout(new java.awt.BorderLayout());

        pnlTop.setPreferredSize(new java.awt.Dimension(553, 65));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/manutencao1.png"))); // NOI18N

        javax.swing.GroupLayout pnlImagemLayout = new javax.swing.GroupLayout(pnlImagem);
        pnlImagem.setLayout(pnlImagemLayout);
        pnlImagemLayout.setHorizontalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImagemLayout.setVerticalGroup(
            pnlImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Formulário de Manutenção de Usuários - AppAssistência");

        javax.swing.GroupLayout pblTituloLayout = new javax.swing.GroupLayout(pblTitulo);
        pblTitulo.setLayout(pblTituloLayout);
        pblTituloLayout.setHorizontalGroup(
            pblTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pblTituloLayout.setVerticalGroup(
            pblTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlLeft.setPreferredSize(new java.awt.Dimension(15, 142));

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        pnlBase.add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pblBottom.setPreferredSize(new java.awt.Dimension(553, 50));

        pnlBotoes.setLayout(new java.awt.GridLayout(1, 5, 5, 5));

        btnAtualiza.setText("Listar Todos");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnAtualiza);

        btnNovoUsuario.setText("Criar Novo");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnNovoUsuario);

        btnDeletarUsuario.setText("Delete");
        btnDeletarUsuario.setEnabled(false);
        btnDeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarUsuarioActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnDeletarUsuario);

        btnAtualizaUsuario.setText("Update");
        btnAtualizaUsuario.setEnabled(false);
        btnAtualizaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaUsuarioActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnAtualizaUsuario);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnCancelar);

        javax.swing.GroupLayout pblBottomLayout = new javax.swing.GroupLayout(pblBottom);
        pblBottom.setLayout(pblBottomLayout);
        pblBottomLayout.setHorizontalGroup(
            pblBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblBottomLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pblBottomLayout.setVerticalGroup(
            pblBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBase.add(pblBottom, java.awt.BorderLayout.PAGE_END);

        pnlRight.setPreferredSize(new java.awt.Dimension(15, 142));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        pnlBase.add(pnlRight, java.awt.BorderLayout.LINE_END);

        pnlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Usuário:"));

        tbDadosUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Email", "Login", "Perfil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDadosUsuarios.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbDadosUsuariosPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbDadosUsuarios);

        lblFiltro.setText("Filtrar pelo Nome:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(lblFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFiltro)
                    .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFiltro)
                        .addComponent(btnFiltrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBase.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed

        // Definem uma arraylist para receber os dados do controller
        // Executam uma operação para atribuir a esta lista, o resultado
        // da listagem de registros do controller
        UsuarioController op = new UsuarioController();
        ArrayList<UsuarioModel> listaUsuarios = new ArrayList<UsuarioModel>();
        listaUsuarios = op.listarRegistrosController();

        //Utilizar um método para capturar o modelo da tabela (disposição
        //da ordem das colunas, quantidade de linhas..
        DefaultTableModel tableModel = (DefaultTableModel) tbDadosUsuarios.getModel();
        // Iterator -> método iterator
        // Documentação disponivel junto ao site da Oracle
        // Descrição do método e a validação de como ele funciona
        // Desafio para a proxima aula!
        Iterator<UsuarioModel> iterator = listaUsuarios.iterator();

        //Método Rian de Solução de tabelas que não querem 
        //ter suas linhas apagadas pelos métodos tradicionais
        while (tableModel.getRowCount() > 0) {
            int i = 0;
            tableModel.removeRow(i);
        }

        while (iterator.hasNext()) {
            UsuarioModel usuario = iterator.next();

            tableModel.addRow(
                    new Object[]{
                        usuario.getId(),
                        usuario.getUserName(),
                        usuario.getEmail(),
                        usuario.getLogin(),
                        usuario.getPerfil()
                    }
            );

        }

    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        //Capturar a informação do texto digitado no campo filtro
        String nome = txtNomeFiltro.getText();

        // Definem uma arraylist para receber os dados do controller
        // Executam uma operação para atribuir a esta lista, o resultado
        // da listagem de registros do controller
        UsuarioController op = new UsuarioController();
        ArrayList<UsuarioModel> listaUsuarios = new ArrayList<UsuarioModel>();
        listaUsuarios = op.filtrarRegistrosController(nome);

        //Utilizar um método para capturar o modelo da tabela (disposição
        //da ordem das colunas, quantidade de linhas..
        DefaultTableModel tableModel = (DefaultTableModel) tbDadosUsuarios.getModel();
        // Iterator -> método iterator
        // Documentação disponivel junto ao site da Oracle
        // Descrição do método e a validação de como ele funciona
        // Desafio para a proxima aula!
        Iterator<UsuarioModel> iterator = listaUsuarios.iterator();

        //Método Rian de Solução de tabelas que não querem 
        //ter suas linhas apagadas pelos métodos tradicionais
        while (tableModel.getRowCount() > 0) {
            int i = 0;
            tableModel.removeRow(i);
        }

        while (iterator.hasNext()) {
            UsuarioModel usuario = iterator.next();

            tableModel.addRow(
                    new Object[]{
                        usuario.getId(),
                        usuario.getUserName(),
                        usuario.getEmail(),
                        usuario.getLogin(),
                        usuario.getPerfil()
                    }
            );

        }


    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        TelaNovoUsuario tela = new TelaNovoUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnDeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarUsuarioActionPerformed
        //Capturar o numero da linha que foi selecionada pelo usuário
        Integer linhaSelec = tbDadosUsuarios.getSelectedRow();
        String idUser = tbDadosUsuarios.getValueAt(linhaSelec, 0).toString();
        String nome = tbDadosUsuarios.getValueAt(linhaSelec, 1).toString();
        String mensagem = "Deseja realmente excluir o registro de: " + nome + " ?";
        Integer numRetorno = JOptionPane.showConfirmDialog(null, mensagem);

        if (numRetorno.equals(0)) {
            UsuarioController op = new UsuarioController();
            op.excluirRegistroController(idUser);
            String msgeExclusao = "Registro excluído com sucesso!";
            JOptionPane.showMessageDialog(null, msgeExclusao);
        } else {
            String msgeDesistencia = "Operação cancelada!";
            JOptionPane.showMessageDialog(null, msgeDesistencia);
        }
    }//GEN-LAST:event_btnDeletarUsuarioActionPerformed

    private void btnAtualizaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaUsuarioActionPerformed

        Integer linhaSelec = tbDadosUsuarios.getSelectedRow();
        //Recuperação dos dados da tabela
        String idUser = tbDadosUsuarios.getValueAt(linhaSelec, 0).toString();
        String userName = tbDadosUsuarios.getValueAt(linhaSelec, 1).toString();
        String email = tbDadosUsuarios.getValueAt(linhaSelec, 2).toString();
        String login = tbDadosUsuarios.getValueAt(linhaSelec, 3).toString();
        String perfil = tbDadosUsuarios.getValueAt(linhaSelec, 4).toString();

        //Abrir nova tela e enviar dados para a tela AtualizaUsuário
        TelaAtualizaUsuario tela = new TelaAtualizaUsuario();
        tela.setVisible(true);
        tela.popularCamposUsuario(idUser, userName, email, login, perfil);
    }//GEN-LAST:event_btnAtualizaUsuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tbDadosUsuariosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbDadosUsuariosPropertyChange
        // TODO add your handling code here:
        if(tbDadosUsuarios.getSelectionModel().isSelectionEmpty()){
                btnAtualizaUsuario.setEnabled(false);
                btnDeletarUsuario.setEnabled(false);
            }else{
                btnAtualizaUsuario.setEnabled(true);
                btnDeletarUsuario.setEnabled(true);
            
            }
    }//GEN-LAST:event_tbDadosUsuariosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOperCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOperCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOperCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOperCadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOperCadastroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnAtualizaUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletarUsuario;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pblBottom;
    private javax.swing.JPanel pblTitulo;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlImagem;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tbDadosUsuarios;
    private javax.swing.JTextField txtNomeFiltro;
    // End of variables declaration//GEN-END:variables
}
